{{- if and (hasKey .Values.envFile "content") (hasKey .Values.config "DRONE_RUNNER_ENV_FILE") }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "droneRunner.labels" . | nindent 4 }}
  name: {{ include "droneRunner.fullname" . }}
data:
  custom-env-vars: |
    {{- .Values.envFile.content | nindent 4 }}
{{- end }}