kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "droneRunner.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update