apiVersion: v1
kind: Secret
metadata:
  name: {{ include "droneRunner.fullname" . }}
type: Opaque
stringData:

  {{- if not (hasKey .Values "config") -}}
  {{- $_ := set .Values "config" dict -}}
  {{- end -}}

  {{- if not (hasKey .Values.config "DRONE_NAMESPACE_DEFAULT") -}}
  {{- $_ := set .Values.config "DRONE_NAMESPACE_DEFAULT" .Release.Namespace -}}
  {{- end -}}

  {{/* SETUP CONFIG */}}
  {{ range $key, $value := .Values.config }}
  {{ upper $key}}: {{ quote $value }}
  {{ end }}
